# ── Stage 1: install all deps (dev + prod) needed for the build ──────────────
FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./
# Full install — devDeps like @faker-js/faker are bundled into route code
RUN npm ci

# ── Stage 2: build ────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# This image is always deployed in postgres mode — Supabase is only used on
# Vercel.  Setting DB_PROVIDER=postgres here prevents db.ts from requiring
# Supabase env vars at build time.
ENV DB_PROVIDER=postgres

# Bake a placeholder URL for NEXT_PUBLIC_* client-side substitution.
# All server-side uses of NEXT_PUBLIC_BASE_URL read from the runtime env
# (injected by the k8s ConfigMap), so this only matters for browser bundles.
ENV NEXT_PUBLIC_BASE_URL=http://localhost:3000

# build:docker uses webpack (not Turbopack) which supports output:'standalone'.
# The regular `npm run build` uses Turbopack for fast local iteration but
# silently skips standalone output, so we keep a separate Docker script.
RUN npm run build:docker

# ── Stage 3: minimal production runner ────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# standalone/ is a self-contained Node server generated by output:'standalone'
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static     ./.next/static
COPY --from=builder /app/public           ./public

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
